apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-devhub
  title: Intro to Dev Hub
  description: |
    Introduction to Developer Hub
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - developerhub
spec:
  type: module
  lifecycle: production
  owner: group:default/workshop-admins
  subcomponentOf: component:default/workshop-repository
